name: AtCoder Backup

on:
  workflow_dispatch: # 手動実行
  schedule:
    - cron: '0 15 * * *' # 日本時間 00:00

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python fetch_submissions.py

      - name: Commit and Push
        run: |
          git config user.name  "ny000815"
          git config user.email "66006097+ny000815@users.noreply.github.com"
          git add - A
          if ! git diff --staged --quiet; then
            git commit -m "Auto backup: $(date)"
            git push
          fi
